---
title: "DMP"
output: html_document
---

Data Management Plan

I.- Types of data generated

The research will generate abundance estimates for mammals, birds, percentage of coverage of plants described in each quadrat, individuals count for freshwater invertebrates and terrestrial invertebrates for each transect, kick sampling station, moth trap and any other respective method (see method). The reduce data, use for the analysis in this report, consist in simplified observation from the principal subsets into presence / absence. Both, raw data subsets and simplified data is published in the GitHub repository.

II.- Types of data preserved

All data described above will be preserved only in the GitHub repository, OneDrive folder shared among the participants of the MSc Ecology Evolution and Biodiversity 25/26 (teachers and students), and personal laptops of every student. However, simplified data across student might vary.

III.- Software and metadata implications

Data curation and graphs were made in R (v. 2025.09.1) [15]. Maps were generated using QGis (v. 3.30.2-'s-Hertogenbosch) [16]. The National British Grid was used as georeferenced system in all maps. Shape files used for each map (eg. Scotland, Hydrographic network, Roads) were downloaded from Digimap [17].

IV.- Length of data preservation

All data collected during the field survey, and by its nature cannot be re-measured, will be preserve indefinitely in the GitHub repository. Data retrieved from desk work survey (see methods), Shapefiles and other similar resources downloaded from [11, 12, 17, see references] will be preserve for at least 10 years.

V.- Value of data to others

Specify and justify which data will have value to others and should be shared. Any data that is shared should be of a sufficiently high quality to be of value to other researchers. In general, published data – data that is displayed or otherwise referred to in a publication – should be made publicly available, but it is for applicants to consider and justify which types of data will, in the context of their project, meaningfully and practically constitute published data. Publicly available means available to anyone, but there may be a requirement for registration to enable tracking of data use and to provide notification of terms and conditions of use where they apply.
Other data should be made available wherever it is appropriate and cost-effective to do so, taking into account the cost of curation compared with the cost or feasibility of re-creation, the potential long-term demand for the data and the feasibility of their reuse by others.

VI.- Length of proprietary period

Length of property of the data collected in the field (described above) will be expired from date of submission of this report. GitHub repository with all documents, folders, resources and data will be available from the same date.

VII.- How data will be shared

Data is shared publicly and available online in the GitHub repository of this report, with absolutely no restriction.

VIII.- Resources needed to preserve and share data

Specify and justify any resources required to preserve and share the data. Wherever possible, data management should make use of existing skills and capabilities. However, justification should be made for any additional specialist staff (or training for existing staff) needed within the grant to enable the research team to manage, preserve and share data effectively; and for any computational facilities needed to manage, store and share the data generated by the research.
No resources are required to preserve and share the data. It is open access and available online in the GitHub repository.
The R scrip for data curation and graphs generation in R (openly available in GitHub repository) is considered to be of basic knowledge, as no complicate packages or functions were used. Idem for maps generation in QGis. Minimums requirement to run the script and reproduce the maps should be the minimum requirements suggested by each software [15, 16 ,see references]